"""init database

Revision ID: da146284c5a0
Revises: 4fb4b58a4d4c
Create Date: 2020-11-21 13:28:24.117998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da146284c5a0'
down_revision = '4fb4b58a4d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
